[project]
name = "modeltester"
version = "0.1.0"
description = ""
authors = [
    {name = "dhrutiweye",email = "dhrutiman.sethi@wheelseye.com"}
]
readme = "README.md"
requires-python = "==3.10.12"
dependencies = [
    "model @ ../../libs/model",
    "database @ ../../libs/database",
    "llm-agent @ ../../libs/llm_agent",
    "vector-db @ ../../libs/vector_db"
]

[tool.poetry]
packages = [{include = "modeltester", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
