[project]
name = "spech-to-text"
version = "0.1.0"
description = ""
authors = [
    {name = "dhrutiweye",email = "dhrutiman.sethi@wheelseye.com"}
]
readme = "README.md"
requires-python = "==3.10.12"
dependencies = [
    "sarvamai (>=0.1.21,<0.2.0)",
    "helper @ ../helper"
]

[tool.poetry]
packages = [{include = "spech_to_text", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
